### ISSUE TITLE
AttributeError: module 'displayio' has no attribute 'Fourwire`

### ISSUE THREAD

**Issue by miloit** [adafruit/Adafruit_CircuitPython_DisplayIO_SSD1306#28]
Hello,

this is the example code
```python
# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
# SPDX-License-Identifier: MIT

"""
This test will initialize the display using displayio and draw a solid white
background, a smaller black rectangle, and some white text.
"""

import board
import displayio
import terminalio
from adafruit_display_text import label
import adafruit_displayio_ssd1306

displayio.release_displays()

oled_reset = board.D9

# Use for I2C
i2c = board.I2C()
display_bus = displayio.I2CDisplay(i2c, device_address=0x3C, reset=oled_reset)

# Use for SPI
# spi = board.SPI()
# oled_cs = board.D5
# oled_dc = board.D6
# display_bus = displayio.FourWire(spi, command=oled_dc, chip_select=oled_cs,
#                                 reset=oled_reset, baudrate=1000000)

WIDTH = 128
HEIGHT = 32  # Change to 64 if needed
BORDER = 5

display = adafruit_displayio_ssd1306.SSD1306(display_bus, width=WIDTH, height=HEIGHT)

# Make the display context
splash = displayio.Group()
display.show(splash)

color_bitmap = displayio.Bitmap(WIDTH, HEIGHT, 1)
color_palette = displayio.Palette(1)
color_palette[0] = 0xFFFFFF  # White

bg_sprite = displayio.TileGrid(color_bitmap, pixel_shader=color_palette, x=0, y=0)
splash.append(bg_sprite)

# Draw a smaller inner rectangle
inner_bitmap = displayio.Bitmap(WIDTH - BORDER * 2, HEIGHT - BORDER * 2, 1)
inner_palette = displayio.Palette(1)
inner_palette[0] = 0x000000  # Black
inner_sprite = displayio.TileGrid(
    inner_bitmap, pixel_shader=inner_palette, x=BORDER, y=BORDER
)
splash.append(inner_sprite)

# Draw a label
text = "Hello World!"
text_area = label.Label(
    terminalio.FONT, text=text, color=0xFFFFFF, x=28, y=HEIGHT // 2 - 1
)
splash.append(text_area)

while True:
    pass
```
but I get this error

```
Traceback (most recent call last):
  File "/home/pi/test.py", line 13, in <module>
    import adafruit_displayio_ssd1306
  File "/usr/local/lib/python3.9/dist-packages/adafruit_displayio_ssd1306.py", line 60, in <module>
    class SSD1306(displayio.Display):
  File "/usr/local/lib/python3.9/dist-packages/adafruit_displayio_ssd1306.py", line 71, in SSD1306
    self, bus: Union[displayio.Fourwire, displayio.I2CDisplay], **kwargs
AttributeError: module 'displayio' has no attribute 'Fourwire'
```

**Comment by tekktrik** [comment]
This is caused by a faulty type annotation, I can submit the fix now.
